import turtle
#David
#LETRA D
turtle.shape('turtle')
turtle.up()
turtle.goto(-790,0)
turtle.down()
turtle.shape('turtle')
turtle.pencolor('black')
turtle.pensize(10)
turtle.forward(200)
turtle.left(50)
turtle.shape('turtle')
turtle.pencolor('black')
turtle.forward(200)
turtle.left(40)
turtle.shape('turtle')
turtle.pencolor('black')
turtle.forward(200)
turtle.left(50)
turtle.shape('turtle')
turtle.pencolor('black')
turtle.forward(200)
turtle.left(40)
turtle.shape('turtle')
turtle.pencolor('black')
turtle.forward(180)
turtle.left(90)
turtle.shape('turtle')
turtle.pencolor('black')
turtle.forward(480)
turtle.left(90)
#LETRA a
turtle.up()
turtle.goto(-100,0)
turtle.down()
turtle.left(90)
turtle.forward(200)
turtle.shape('turtle')
turtle.pencolor('silver')
turtle.left(45)
turtle.forward(200)
turtle.shape('turtle')
turtle.pencolor('silver')
turtle.left(90)
turtle.forward(200)
turtle.shape('turtle')
turtle.pencolor('silver')
turtle.left(90)
turtle.forward(200)
turtle.shape('turtle')
turtle.pencolor('silver')
turtle.left(90)
turtle.forward(200)
turtle.left(45)
#LETRA v
turtle.up()
turtle.goto(-30,350)
turtle.down()
turtle.shape('turtle')
turtle.pencolor('red')
turtle.left(200)
turtle.forward(350)
turtle.shape('turtle')
turtle.pencolor('red')
turtle.left(-210)
turtle.forward(350)
#LETRA i
turtle.up()
turtle.goto(250,400)
turtle.down()
turtle.dot(80,'pink')
turtle.up()
turtle.goto(250,350)
turtle.down()
turtle.shape('turtle')
turtle.pencolor('blue')
turtle.left(-170)
turtle.forward(340)
#LETRA d
turtle.up()
turtle.goto(640,0)
turtle.down()
turtle.left(180)
turtle.forward(200)
turtle.shape('turtle')
turtle.pencolor('orange')
turtle.left(45)
turtle.forward(200)
turtle.shape('turtle')
turtle.pencolor('orange')
turtle.left(90)
turtle.forward(200)
turtle.shape('turtle')
turtle.pencolor('orange')
turtle.left(90)
turtle.forward(200)
turtle.shape('turtle')
turtle.pencolor('orange')
turtle.left(90)
turtle.forward(200)
turtle.shape('turtle')
turtle.pencolor('orange')
turtle.left(45)
turtle.forward(300)
#firma
turtle.up()
turtle.goto(-790,-45)
turtle.down()
turtle.shape('turtle')
turtle.pencolor('green')
turtle.left(-90)
turtle.forward(1500)





